
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'sentenceACTION ENTITY GROUP IDENTIFIER MODIFIER RELATION SPECIFIC\n    sentence : ACTION ENTITY RELATION MODIFIER SPECIFIC GROUP\n             | ACTION ENTITY RELATION MODIFIER SPECIFIC\n             | ACTION ENTITY RELATION MODIFIER\n             | ACTION ENTITY RELATION\n             | ACTION ENTITY\n             | ACTION\n    '
    
_lr_action_items = {'ACTION':([0,],[2,]),'$end':([1,2,3,4,5,6,7,],[0,-6,-5,-4,-3,-2,-1,]),'ENTITY':([2,],[3,]),'RELATION':([3,],[4,]),'MODIFIER':([4,],[5,]),'SPECIFIC':([5,],[6,]),'GROUP':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> ACTION ENTITY RELATION MODIFIER SPECIFIC GROUP','sentence',6,'p_sentence','regles.py',69),
  ('sentence -> ACTION ENTITY RELATION MODIFIER SPECIFIC','sentence',5,'p_sentence','regles.py',70),
  ('sentence -> ACTION ENTITY RELATION MODIFIER','sentence',4,'p_sentence','regles.py',71),
  ('sentence -> ACTION ENTITY RELATION','sentence',3,'p_sentence','regles.py',72),
  ('sentence -> ACTION ENTITY','sentence',2,'p_sentence','regles.py',73),
  ('sentence -> ACTION','sentence',1,'p_sentence','regles.py',74),
]
